### ISSUE TITLE
How do you think about random the account list each time when GitHub star Repo?

### ISSUE THREAD

**Issue by EyreFree** [PY-Trade/PY-Login#1]
![VSCAM](http://upload-images.jianshu.io/upload_images/1018190-01f7b2bb2956124b.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![EFQRCode](http://upload-images.jianshu.io/upload_images/1018190-097b915fcd76cbf3.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

It seems to be a little bit fake if each time same order, 🤔.

**Comment by ookcode** [comment]
Good advice, i append this function.
