### ISSUE TITLE
How to get the encrypt method of password

### ISSUE THREAD

**Issue by martin-ding** [PY-Trade/PY-Login#2]
HI ookcode

Your code is absolute awesome ! 
Now I am confusing that how could you find the way to encrypt the password such as the encrypt code of Bilibili password as follow 
```
def _encrypt(self, password):
	#获取加密的token
	response = self.get('http://passport.bilibili.com/login?act=getkey')
	token = json.loads(response.content.decode('utf-8'))
	password = str(token['hash'] + password).encode('utf-8')
	pub_key = token['key']
	pub_key = rsa.PublicKey.load_pkcs1_openssl_pem(pub_key)
	message = rsa.encrypt(password, pub_key)
	message = binascii.b2a_base64(message)
	return message
```
Could you give me some tips?

**Comment by ookcode** [comment]
还是用中文吧，毕竟是个中文项目。

很遗憾，我并不是通过观察加密后的密码值来猜出加密方式的。

Bilibili有提供开放的API，而且我也是在别人的项目上看到的。囧

http://api.bilibili.com
http://docs.bilibili.cn

如果打不开可以尝试用网络时光机
http://archive.org（需要梯子）

**Comment by martin-ding** [comment]
hi ookcode

我发现了这个链接 https://github.com/fython/BilibiliAPIDocs

谢谢
